config/routes.rb
Rails.application.routes.draw do
  devise_for :users
root "pages#home"

get "about" => "pages#about"

get "mission" =>"pages#mission"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def mission
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<body background="http://s6.favim.com/orig/150313/background-flores-flowers-pale-Favim.com-2559326.jpg">
<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "HERITAGE", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <font face = "lato">
         <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Mission", mission_path %></li>
                  <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path%></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            </ul>
            <%end%>
   </nav>
   <% if user_signed_in? %>
   <% else %>
  <div class="container">
<div align ="right">
            <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-sm" %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-sm" %>
            <%end%>
</div>
</div>
  </div><!-- /.container-fluid -->


</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HERITAGE</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>	

	<%= render 'layouts/header'%>
	<style>
h1   {color:black;}
p    {color:black}
</style>
		<div class="container">
				<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-info")%>
			<% end %>
			<%= yield %>
		</div>`
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on our One Month Pinteresting app!</p>
<p> Check out <%= link_to "Bing", "https://bing.com", class: "btn btn-primary"%>

app/views/pages/home.html.erb
<center>
	
		<b><font face = "playfair display";font color = "white"; size = "90" >
			H E R I T A G E
		 </font></b>
		 <font face = "lato";font color = "white"; size = "90" >
		 	&nbsp;
		 	<b>
		 		COLLECTION
		 	</b>
		 	</font>
		

<iframe src="https://player.vimeo.com/video/145745241?autoplay=1&title=0&byline=0&portrait=0" width="1000" height="427" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</center>

app/views/pages/mission.html.erb
<div align "center">
	<h1>Mission</h1>
	<p>Pinning your interests in an easily accessed place</p>
</div>